version: '3.3'
services:
    db:
      image: mysql:8.0
      container_name: mysql8
      restart: always
      environment:
        MYSQL_DATABASE: 'db'
        # So you don't have to use root, but you can if you like
        MYSQL_USER: 'dev'
        # You can use whatever password you like
        MYSQL_PASSWORD: 'ax2'
        # Password for root access
        MYSQL_ROOT_PASSWORD: 'root'
      ports:
        # <Port exposed> : < MySQL Port running inside container>
        - '3306:3306'
      expose:
        # Opens port 3306 on the container
        - '3306'
        # Where our data will be persisted
      volumes:
        - ./data:/var/lib/mysql
# Names our volume
volumes:
    my-db:

# cli commands:
# docker-compose up
# docker exec -it mysql8 bash
# mysql -u dev -pax2